#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Android dev/build wrapper for Drugucopia Tauri app
#
# Auto-detects the Android NDK and sets CARGO_TARGET_*_LINKER env vars
# so Cargo uses the correct cross-linker instead of /usr/bin/ld.
#
# Usage:
#   bash scripts/android.sh dev        # build & run on device/emulator
#   bash scripts/android.sh build      # build release APK
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ACTION="${1:-dev}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[android]${NC} $*"; }
ok()    { echo -e "${GREEN}[android]${NC} $*"; }
die()   { echo -e "${RED}[android]${NC} $*" >&2; exit 1; }

# ─── 1. Find Android NDK ─────────────────────────────────────────────────────
info "Looking for Android NDK..."

NDK_PATH=""

for var in ANDROID_NDK_HOME NDK_HOME; do
  val="${!var:-}"
  if [ -n "$val" ] && [ -d "$val" ]; then
    NDK_PATH="$val"
    ok "Found via $var: $NDK_PATH"
    break
  fi
done

if [ -z "$NDK_PATH" ] && [ -n "${ANDROID_HOME:-}" ]; then
  NDK_PATH=$(ls -d "$ANDROID_HOME/ndk/"* 2>/dev/null | sort -V | tail -1 || true)
fi

if [ -z "$NDK_PATH" ]; then
  for dir in \
    "$HOME/Android/Sdk" \
    "$HOME/android-sdk" \
    "$HOME/.android/sdk" \
    "/opt/android-sdk" \
    "/usr/local/android-sdk"; do
    if [ -d "$dir/ndk" ]; then
      NDK_PATH=$(ls -d "$dir/ndk/"* 2>/dev/null | sort -V | tail -1 || true)
      [ -n "$NDK_PATH" ] && break
    fi
    if [ -d "$dir/ndk-bundle" ]; then
      NDK_PATH="$dir/ndk-bundle"
      break
    fi
  done
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_PROPS="$SCRIPT_DIR/../src-tauri/gen/android/local.properties"
if [ -z "$NDK_PATH" ] && [ -f "$LOCAL_PROPS" ]; then
  NDK_PATH=$(grep -oP '(?<=ndk\.dir=).*' "$LOCAL_PROPS" 2>/dev/null | head -1 || true)
  if [ -n "$NDK_PATH" ] && [ ! -d "$NDK_PATH" ]; then
    NDK_PATH=""
  fi
fi

if [ -z "$NDK_PATH" ]; then
  die "Android NDK not found!

  Set one of these environment variables:
    export ANDROID_NDK_HOME=/path/to/ndk
    export ANDROID_HOME=/path/to/sdk   (must have ndk/<version> inside)

  Or install the NDK via Android Studio:
    Tools > SDK Manager > SDK Tools > NDK (Side by side)"
fi

ok "NDK: $NDK_PATH"

# ─── 2. Detect host tag ──────────────────────────────────────────────────────
case "$(uname -s)" in
  Linux)   HOST_TAG="linux-x86_64" ;;
  Darwin)  HOST_TAG="darwin-x86_64" ;;
  MINGW*|MSYS*|CYGWIN*) HOST_TAG="windows-x86_64" ;;
  *)       die "Unsupported OS: $(uname -s)" ;;
esac

TOOLCHAIN="$NDK_PATH/toolchains/llvm/prebuilt/$HOST_TAG"
if [ ! -d "$TOOLCHAIN" ]; then
  die "NDK toolchain not found at: $TOOLCHAIN"
fi

ok "Toolchain: $TOOLCHAIN"

# ─── 3. Detect API level ─────────────────────────────────────────────────────
API_LEVEL=""
for level in 34 33 32 31 30 29 28; do
  if [ -f "$TOOLCHAIN/bin/aarch64-linux-android${level}-clang" ]; then
    API_LEVEL=$level
    break
  fi
done
if [ -z "$API_LEVEL" ]; then
  API_LEVEL=33
  info "Defaulting to API level $API_LEVEL"
else
  ok "API level: $API_LEVEL"
fi

# ─── 4. Install Rust targets ─────────────────────────────────────────────────
info "Checking Rust Android targets..."
for target in aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android; do
  if ! rustup target list --installed 2>/dev/null | grep -q "$target"; then
    info "Installing $target..."
    rustup target add "$target" 2>/dev/null || true
  fi
done
ok "Rust targets ready"

# ─── 5. Set Cargo linker env vars ────────────────────────────────────────────
export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$TOOLCHAIN/bin/aarch64-linux-android${API_LEVEL}-clang"
export CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER="$TOOLCHAIN/bin/armv7a-linux-androideabi${API_LEVEL}-clang"
export CARGO_TARGET_I686_LINUX_ANDROID_LINKER="$TOOLCHAIN/bin/i686-linux-android${API_LEVEL}-clang"
export CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER="$TOOLCHAIN/bin/x86_64-linux-android${API_LEVEL}-clang"

ok "Linker env vars set"

# ─── 6. Write .cargo/config.toml as fallback ──────────────────────────────────
CARGO_CFG_DIR="$SCRIPT_DIR/../src-tauri/.cargo"
CARGO_CFG="$CARGO_CFG_DIR/config.toml"
mkdir -p "$CARGO_CFG_DIR"
cat > "$CARGO_CFG" <<EOF
# Auto-generated by scripts/android.sh
[target.aarch64-linux-android]
linker = "${CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER}"

[target.armv7-linux-androideabi]
linker = "${CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER}"

[target.i686-linux-android]
linker = "${CARGO_TARGET_I686_LINUX_ANDROID_LINKER}"

[target.x86_64-linux-android]
linker = "${CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER}"
EOF

# ─── 7. Clean stale artifacts ────────────────────────────────────────────────
for arch in armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android; do
  rm -f "$SCRIPT_DIR/../src-tauri/target/$arch/debug/deps/libdrugucopia_lib"*.so 2>/dev/null || true
done

# ─── 8. Detect LAN IP for device access ──────────────────────────────────────
# 'serve' listens on 0.0.0.0 by default. The Android device reaches it
# via the host's LAN IP, which Tauri rewrites into the devUrl.
LAN_IP=""
if command -v ip &>/dev/null; then
  LAN_IP=$(ip route get 1 2>/dev/null | grep -oP 'src \K\S+' | head -1 || true)
elif command -v ifconfig &>/dev/null; then
  LAN_IP=$(ifconfig 2>/dev/null | grep 'inet ' | grep -v 127.0.0.1 | awk '{print $2}' | head -1 || true)
fi

if [ -n "$LAN_IP" ]; then
  ok "LAN IP: $LAN_IP"
  export TAURI_DEV_HOST="$LAN_IP"
else
  info "Could not auto-detect LAN IP."
  info "If the app doesn't load on device, set it manually:"
  info "  export TAURI_DEV_HOST=192.168.x.x"
fi

# ─── 9. Run Tauri ────────────────────────────────────────────────────────────
cd "$SCRIPT_DIR/.."

case "$ACTION" in
  dev)
    info "Starting tauri android dev..."
    npx tauri android dev
    ;;
  build)
    info "Building release APK..."
    npx tauri android build
    ;;
  *)
    die "Unknown action: $ACTION  (use 'dev' or 'build')"
    ;;
esac
