#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Android setup script for Drugucopia Tauri app
#
# This script:
#   1. Auto-detects your Android NDK installation
#   2. Installs the required Rust Android targets
#   3. Generates .cargo/config.toml with the correct NDK linker paths
#
# Usage:  ./scripts/setup-android.sh
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CARGO_CONFIG_DIR="$PROJECT_ROOT/src-tauri/.cargo"
CARGO_CONFIG="$CARGO_CONFIG_DIR/config.toml"

# ─── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ─── 1. Detect Android NDK ────────────────────────────────────────────────────
info "Detecting Android NDK..."

NDK_PATH=""

# Check ANDROID_NDK_HOME first
if [ -n "${ANDROID_NDK_HOME:-}" ] && [ -d "$ANDROID_NDK_HOME" ]; then
  NDK_PATH="$ANDROID_NDK_HOME"
  ok "ANDROID_NDK_HOME is set: $NDK_PATH"
fi

# Check NDK_HOME
if [ -z "$NDK_PATH" ] && [ -n "${NDK_HOME:-}" ] && [ -d "$NDK_HOME" ]; then
  NDK_PATH="$NDK_HOME"
  ok "NDK_HOME is set: $NDK_PATH"
fi

# Search ANDROID_HOME/ndk/<version>/
if [ -z "$NDK_PATH" ] && [ -n "${ANDROID_HOME:-}" ]; then
  NDK_PATH=$(ls -d "$ANDROID_HOME/ndk/"* 2>/dev/null | sort -V | tail -1 || true)
  if [ -n "$NDK_PATH" ]; then
    ok "Found NDK in ANDROID_HOME: $NDK_PATH"
  fi
fi

# Search common install locations
if [ -z "$NDK_PATH" ]; then
  for dir in \
    "$HOME/Android/Sdk" \
    "$HOME/android-sdk" \
    "$HOME/.android/sdk" \
    "/opt/android-sdk" \
    "/usr/local/android-sdk"; do
    if [ -d "$dir/ndk" ]; then
      NDK_PATH=$(ls -d "$dir/ndk/"* 2>/dev/null | sort -V | tail -1 || true)
      if [ -n "$NDK_PATH" ]; then
        ok "Found NDK at: $NDK_PATH"
        break
      fi
    fi
  done
fi

# Check Android Studio's default location
if [ -z "$NDK_PATH" ]; then
  AS_SDK="$HOME/Android/Sdk"
  if [ -d "$AS_SDK" ]; then
    NDK_PATH=$(ls -d "$AS_SDK/ndk/"* 2>/dev/null | sort -V | tail -1 || true)
  fi
fi

if [ -z "$NDK_PATH" ]; then
  error "Could not find Android NDK. Set ANDROID_NDK_HOME or ANDROID_HOME and re-run.
        
        Install the NDK via Android Studio:
          Tools > SDK Manager > SDK Tools tab > NDK (Side by side)
        
        Or via command line:
          sdkmanager --install 'ndk;27.0.12077973'
        
        Then set the environment variable:
          export ANDROID_NDK_HOME=\$HOME/Android/Sdk/ndk/27.0.12077973"
fi

# Validate NDK has the toolchain
HOST_TAG=""
case "$(uname -s)" in
  Linux)   HOST_TAG="linux-x86_64" ;;
  Darwin)  HOST_TAG="darwin-x86_64" ;;
  MINGW*|MSYS*|CYGWIN*) HOST_TAG="windows-x86_64" ;;
  *)       error "Unsupported OS: $(uname -s)" ;;
esac

TOOLCHAIN_DIR="$NDK_PATH/toolchains/llvm/prebuilt/$HOST_TAG"
if [ ! -d "$TOOLCHAIN_DIR" ]; then
  error "NDK toolchain directory not found: $TOOLCHAIN_DIR
        Is your NDK installation complete?"
fi

# ─── 2. Detect API level ──────────────────────────────────────────────────────
# Find the highest API level available in the NDK toolchain
API_LEVEL=""
for level in 34 33 32 31 30 29 28; do
  if [ -f "$TOOLCHAIN_DIR/bin/aarch64-linux-android${level}-clang" ]; then
    API_LEVEL=$level
    break
  fi
done

if [ -z "$API_LEVEL" ]; then
  # Fallback: find any clang binary and extract the API level
  API_LEVEL=$(ls "$TOOLCHAIN_DIR/bin/"*android*clang 2>/dev/null | head -1 | grep -oP '\d+(?=-clang)' || true)
fi

if [ -z "$API_LEVEL" ]; then
  warn "Could not auto-detect API level, defaulting to 33"
  API_LEVEL=33
fi

ok "Using API level: $API_LEVEL"
ok "Host tag: $HOST_TAG"
ok "Toolchain: $TOOLCHAIN_DIR"

# ─── 3. Install Rust Android targets ──────────────────────────────────────────
info "Installing Rust Android targets..."

for target in aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android; do
  if rustup target list --installed 2>/dev/null | grep -q "$target"; then
    ok "Target $target already installed"
  else
    info "Installing target $target..."
    rustup target add "$target"
  fi
done

# ─── 4. Generate .cargo/config.toml ──────────────────────────────────────────
info "Generating $CARGO_CONFIG..."

mkdir -p "$CARGO_CONFIG_DIR"

cat > "$CARGO_CONFIG" <<EOF
# Auto-generated by scripts/setup-android.sh
# DO NOT EDIT — re-run the script if you update your NDK.
#
# These linker paths tell Cargo to use the Android NDK's clang
# instead of the host system linker when cross-compiling for Android.

[target.aarch64-linux-android]
linker = "${TOOLCHAIN_DIR}/bin/aarch64-linux-android${API_LEVEL}-clang"

[target.armv7-linux-androideabi]
linker = "${TOOLCHAIN_DIR}/bin/armv7a-linux-androideabi${API_LEVEL}-clang"

[target.i686-linux-android]
linker = "${TOOLCHAIN_DIR}/bin/i686-linux-android${API_LEVEL}-clang"

[target.x86_64-linux-android]
linker = "${TOOLCHAIN_DIR}/bin/x86_64-linux-android${API_LEVEL}-clang"
EOF

ok "Generated $CARGO_CONFIG"

# ─── 5. Summary ──────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Android setup complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo "  NDK:            $NDK_PATH"
echo "  API Level:      $API_LEVEL"
echo "  Host:           $HOST_TAG"
echo "  Cargo config:   $CARGO_CONFIG"
echo ""
echo "  Next steps:"
echo "    npm run tauri:android:dev"
echo ""

